### ISSUE TITLE
IOError: cannot open resource -  fonts

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#101]
Traceback (most recent call last):
  File "info_bot.py", line 7, in <module>
    execute()
  File "/etc/reddit-infobot/reddit_info_bot/cli.py", line 268, in execute
    exitcode = cmd(**cmdargs)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 134, in wrapped
    return do_setup(settings, command, *args, **kwargs)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 117, in do_setup
    command(settings, *a, **kw)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 194, in cmd_run
    handle_bot_action(messages, settings, account1, account2, subreddit_list, comments_seen, 'find_username_mentions')
  File "/etc/reddit-infobot/reddit_info_bot/reddit.py", line 477, in handle_bot_action
    account1=account, account2=account2)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 265, in cmd_imagesearch
    wordcloud_image = cmd_wordcloud(settings, text, from_cli=from_cli, filename=filename)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 309, in cmd_wordcloud
    image, imgsize = wordcloud_image(text, **kwargs)
  File "/etc/reddit-infobot/reddit_info_bot/wcloud.py", line 49, in wordcloud_image
    wc.generate_from_text(text)
  File "/usr/lib64/python2.7/site-packages/wordcloud/wordcloud.py", line 434, in generate_from_text
    self.generate_from_frequencies(words)
  File "/usr/lib64/python2.7/site-packages/wordcloud/wordcloud.py", line 317, in generate_from_frequencies
    font = ImageFont.truetype(self.font_path, font_size)
  File "/usr/lib64/python2.7/site-packages/PIL/ImageFont.py", line 239, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/usr/lib64/python2.7/site-packages/PIL/ImageFont.py", line 128, in __init__
    self.font = core.getfont(font, size, index, encoding)
IOError: cannot open resource

**Comment by nyov** [comment]
This is a config problem: wordcloud can't find the font file.

I haven't provided any font files with the code.
You can use any truetype or opentype font file in `BOTCMD_WORDCLOUD_CONFIG`.
Just find one in windows/system/fonts or /usr/share/fonts, or on any font website.

As per `wordcloud` readme:
> Defaults to DroidSansMono path on a Linux machine. If you are on another OS or don’t have this font, you need to adjust this path.

For example:
```python
BOTCMD_WORDCLOUD_CONFIG = { # Reference: https://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud-wordcloud
    #'font_path': '<ttf_or_otf.path>',
    #'font_path': '/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf',
    # or otf:
    'font_path': '/etc/reddit_info_bot/fonts/Quattrocento-Regular.otf',
    'width': 400,
    'height': 400,
    'scale': 2,
    'max_words': 600,
}
```
These both (Quattro and DejaVu) are the font files we had on the box before. These had some support for kyrillic or other unicode characters if I remember.

**Comment by tek0011** [comment]
I have a font file.  and when i set the font_path setting I get same error.
 although wait.  does it want the ttf or otf?

On Mon, Jul 11, 2016 at 5:11 PM, nyov <notifications@github.com> wrote:

> This is a config problem: wordcloud can't find the font file.
>
> I haven't provided any font files with the code.
> You can use any truetype or opentype font file in BOTCMD_WORDCLOUD_CONFIG.
> Just find one in windows/system/fonts or /usr/share/fonts, or on any font
> website.
>
> As per wordcloud readme:
>
> Defaults to DroidSansMono path on a Linux machine. If you are on another
> OS or don’t have this font, you need to adjust this path.
>
> For example:
>
> BOTCMD_WORDCLOUD_CONFIG = { # Reference: https://amueller.github.io/word_cloud/generated/wordcloud.WordCloud.html#wordcloud-wordcloud
>     #'font_path': '<ttf_or_otf.path>',
>     #'font_path': '/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf',
>     # or otf:
>     'font_path': '/etc/reddit_info_bot/fonts/Quattrocento-Regular.otf',
>     'width': 400,
>     'height': 400,
>     'scale': 2,
>     'max_words': 600,
> }
>
> These both (Quattro and DejaVu) are the font files we had on the box
> before. These had some support for kyrillic or other unicode characters if
> I remember.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/issues/101#issuecomment-231881545>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABCOXAkEVaF2V7dOelFOJPOrNKkUkNWlks5qUr-rgaJpZM4JJx9c>
> .
>



-- 
Jeff

**Comment by nyov** [comment]
Either should be okay, 'ttf' or 'otf'.
The path might need to be absolute (starting from `/`)
