### ISSUE TITLE
AttributeError: '<class 'praw.objects.Message'>' has no attribute 'permalink'

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#102]
```
  File "info_bot.py", line 7, in <module>
    execute()
  File "/etc/reddit-infobot/reddit_info_bot/cli.py", line 268, in execute
    exitcode = cmd(**cmdargs)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 134, in wrapped
    return do_setup(settings, command, *args, **kwargs)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 117, in do_setup
    command(settings, *a, **kw)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 194, in cmd_run
    handle_bot_action(messages, settings, account1, account2, subreddit_list, comments_seen, 'find_username_mentions')
  File "/etc/reddit-infobot/reddit_info_bot/reddit.py", line 470, in handle_bot_action
    keywords = _applicable_comment(comment, settings, account, comments_seen, subreddit_list, search_list, information_reply)
  File "/etc/reddit-infobot/reddit_info_bot/reddit.py", line 347, in _applicable_comment
    logger.debug('[!] %s - comment\'s subreddit is not in our list [%s]' % (comment.id, comment.permalink))
  File "/usr/lib/python2.7/site-packages/praw/objects.py", line 92, in __getattr__
    raise AttributeError(msg)
AttributeError: '<class 'praw.objects.Message'>' has no attribute 'permalink'
```

**Comment by nyov** [comment]
Ow. Crap. Ahjajajaja this is serious bad.
I'm not quite sure how this happened. Or why it hasn't happened before.
This code is in no way a recent change, but it definitely looks broken. Something very strange here.

Perhaps it'll be clearer to me tomorrow. But this might take me some time, sorry.

**Comment by tek0011** [comment]
Thanks friend.

On Tue, Jul 12, 2016 at 10:32 PM, nyov <notifications@github.com> wrote:

> Ow. Crap. Ahjajajaja this is serious bad.
> I'm not quite sure how this happened. Or why it hasn't happened before.
> This code is in no way a recent change, but it definitely looks broken.
> Something very strange here.
>
> Perhaps it'll be clearer to me tomorrow. But this might take me some time,
> sorry.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/issues/102#issuecomment-232247678>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABCOXF__wGOQJ6xkbo0f67mUeVRTQAqRks5qVFw5gaJpZM4JK56J>
> .
>



-- 
Jeff

**Comment by tek0011** [comment]
Heyyyy.  Any ideas on this latest issue?  The bot pretty much crashes and
will not continue, rendering it useless.



On Wed, Jul 13, 2016 at 6:02 AM, Jeff <thecptsparrow@gmail.com> wrote:

> Thanks friend.
>
> On Tue, Jul 12, 2016 at 10:32 PM, nyov <notifications@github.com> wrote:
>
>> Ow. Crap. Ahjajajaja this is serious bad.
>> I'm not quite sure how this happened. Or why it hasn't happened before.
>> This code is in no way a recent change, but it definitely looks broken.
>> Something very strange here.
>>
>> Perhaps it'll be clearer to me tomorrow. But this might take me some
>> time, sorry.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/tek0011/reddit_info_bot/issues/102#issuecomment-232247678>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ABCOXF__wGOQJ6xkbo0f67mUeVRTQAqRks5qVFw5gaJpZM4JK56J>
>> .
>>
>
>
>
> --
> Jeff
>



-- 
Jeff

**Comment by nyov** [comment]
Still digging. While I've found another bug, I couldn't reproduce this one so far :(
Getting closer, though.

**Comment by tek0011** [comment]
i think i could reproduce it just by running the bot again.
if you run the bot are you seeing the first request from indianteens?

On Thu, Jul 14, 2016 at 12:00 PM, nyov <notifications@github.com> wrote:

> Still digging. While I've found another bug, I couldn't reproduce this one
> so far :(
> Getting closer, though.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/issues/102#issuecomment-232726829>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABCOXMxQScKputlRIUxweEUwHLlm1Pwqks5qVmswgaJpZM4JK56J>
> .
>



-- 
Jeff

**Comment by nyov** [comment]
Found it. For a quick workaround, check the bot account inbox messages
and mark all of them read which are **not** "username mention"s but direct PMs.

**Comment by tek0011** [comment]
ummm. i am seeing no direct pms.   http://i.imgur.com/VHIXAP0.png

but at the same time I am not seeing the original username mention from the
link that the bot is failing on.  perhaps because that username
mention no longer exists its crashing?  but then the question is, why would
it be checking that link if the username mention doesnt exist...



On Thu, Jul 14, 2016 at 12:06 PM, nyov <notifications@github.com> wrote:

> Found it. For a quick workaround, check the bot account inbox messages
> and mark all of them read which are *not* "username mention"s but direct
> PMs.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/issues/102#issuecomment-232728295>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABCOXCBFSGC1q056zuFQd5_1FxEUMHoKks5qVmyDgaJpZM4JK56J>
> .
>



-- 
Jeff

**Comment by nyov** [comment]
The one that is not prefixed 'username mention': "Don't forget to verify your email".
That must be the one messing it up.

But don't change anything now, I have a PR ready for testing.

**Comment by tek0011** [comment]
okie dokie :)

On Thu, Jul 14, 2016 at 12:24 PM, nyov <notifications@github.com> wrote:

> The one that is not prefixed 'username mention': "Don't forget to verify
> your email".
> That must be the one messing it up.
>
> But don't change anything now, I have a PR ready for testing.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/issues/102#issuecomment-232733458>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABCOXBp8K-ofq6zlHW4Q1lOSHRgWMzhXks5qVnDdgaJpZM4JK56J>
> .
>



-- 
Jeff
