### ISSUE TITLE
downvoted comments not deleted

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#20]
I have not seen if it downvotes them at -1, but it doesnt at 0

**Comment by jacobstein123** [comment]
The way it's set up is that it will only delete if the score is less than zero. I'll change it to 0 now.

**Comment by tek0011** [comment]
Seems this has popped up again.

**Comment by jacobstein123** [comment]
The bot is set to wait a half hour before deleting. Could that be the cause, or do downvoted comments not get deleted at all?

**Comment by tek0011** [comment]
Seems this has shown up again. 

(nsfw) https://www.reddit.com/r/cumsluts/comments/4awspm/she_wants_it_all_over_her_face/d1476je

maybe its not checking the comments after a certain period of time?  This comment should be deleted though.

**Comment by nyov** [comment]
That was a bug. oops. Praw comment object has no title. No idea why I thought it had...
I pushed a fix. (The linked comment was in fact deleted just now).
