### ISSUE TITLE
isnt info_bot_nsfw_parser supposed to be submitting the links

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#28]
I thought we made it so that info_bot_nsfw_parser was supposed to do all the submission of links to the parsing thread?  I dont want info_bot_nsfw shadowbanned, so I think we need to fix that unless I am wrong.

**Comment by tek0011** [comment]
Still potential issue.

**Comment by nyov** [comment]
Should be fixed now
