### ISSUE TITLE
praw.errors.APIException: (NO_TEXT) `we need something here` on field `text`

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#32]
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 466, in <module>
    main()
  File "info_bot_nsfw.py", line 450, in main
    find_username_mentions()
  File "info_bot_nsfw.py", line 301, in find_username_mentions
    give_more_info(comment)
  File "info_bot_nsfw.py", line 212, in give_more_info
    karmadecay_formatted = format_results(results[3])
  File "info_bot_nsfw.py", line 160, in format_results
    ascii_final = get_nonspam_links(ascii_filtered) #filter the links for spam
  File "info_bot_nsfw.py", line 131, in get_nonspam_links
    submission.add_comment(link)
  File "/usr/local/lib/python2.7/site-packages/praw/objects.py", line 1019, in add_comment
    response = self.reddit_session._add_comment(self.fullname, text)
  File "/usr/local/lib/python2.7/site-packages/praw/decorators.py", line 338, in wrapped
    return function(cls, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/praw/__init__.py", line 2173, in _add_comment
    retry_on_error=False)
  File "/usr/local/lib/python2.7/site-packages/praw/decorators.py", line 189, in wrapped
    raise error_list[0]
praw.errors.APIException: (NO_TEXT) `we need something here` on field `text`

**Comment by tek0011** [comment]
reopening - 

data: {'text': '            </div', 'thing_id': u't3_334fmf'}
posted:             </div


Good tld: True
No spamlinks in link: True
No text spam: True

            IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '           ', 'thing_id': u't3_334fmf'}
Traceback (most recent call last):
  File "info_bot_nsfw.py", line 473, in <module>
    main()
  File "info_bot_nsfw.py", line 457, in main
    find_username_mentions()
  File "info_bot_nsfw.py", line 308, in find_username_mentions
    give_more_info(comment)
  File "info_bot_nsfw.py", line 219, in give_more_info
    karmadecay_formatted = format_results(results[3])
  File "info_bot_nsfw.py", line 160, in format_results
    ascii_final = get_nonspam_links(ascii_filtered) #filter the links for spam
  File "info_bot_nsfw.py", line 131, in get_nonspam_links
    submission.add_comment(link)
  File "/usr/local/lib/python2.7/site-packages/praw/objects.py", line 1019, in add_comment
    response = self.reddit_session._add_comment(self.fullname, text)
  File "/usr/local/lib/python2.7/site-packages/praw/decorators.py", line 338, in wrapped
    return function(cls, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/praw/__init__.py", line 2173, in _add_comment
    retry_on_error=False)
  File "/usr/local/lib/python2.7/site-packages/praw/decorators.py", line 189, in wrapped
    raise error_list[0]
praw.errors.APIException: (NO_TEXT) `we need something here` on field `text`

**Comment by tek0011** [comment]
Here is what the api/html returns look like sometimes.  Pretty sure its what causes the error above:


retrieving: http://www.reddit.com/message/unread/.json
params: {'limit': 40}
data: None
passed domains: []
KARMA DECAY:
ic "-//w3c//dtd xhtml 1.0 transitional//en" "http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"
Good tld: True
No spamlinks in link: True
No text spam: True

ic "-//w3c//dtd xhtml 1.0 transitional//en" "http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': 'ic "-//w3c//dtd xhtml 1.0 transitional//en" "http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"', 'thing_id': u't3_334fmf'}
posted: ic "-//w3c//dtd xhtml 1.0 transitional//en" "http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml"

    <head
Good tld: True
No spamlinks in link: True
No text spam: True

    <head IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '    <head', 'thing_id': u't3_334fmf'}
posted:     <head

        <meta http-equiv="content-type" content="text/html; charset=utf-8" /
Good tld: True
No spamlinks in link: True
No text spam: True

        <meta http-equiv="content-type" content="text/html; charset=utf-8" / IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '        <meta http-equiv="content-type" content="text/html; charset=utf-8" /', 'thing_id': u't3_334fmf'}
posted:         <meta http-equiv="content-type" content="text/html; charset=utf-8" /

        <meta name="robots" content="nosnippet" /
Good tld: True
No spamlinks in link: True
No text spam: True

        <meta name="robots" content="nosnippet" / IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '        <meta name="robots" content="nosnippet" /', 'thing_id': u't3_334fmf'}
posted:         <meta name="robots" content="nosnippet" /

        <title>karma decay - reverse image search of reddit.com</title
Good tld: True
No spamlinks in link: True
No text spam: True

        <title>karma decay - reverse image search of reddit.com</title IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '        <title>karma decay - reverse image search of reddit.com</title', 'thing_id': u't3_334fmf'}
posted:         <title>karma decay - reverse image search of reddit.com</title

        <meta name="description" content="karma decay. reverse image search of reddit.com." /
Good tld: True
No spamlinks in link: True
No text spam: True

        <meta name="description" content="karma decay. reverse image search of reddit.com." / IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '        <meta name="description" content="karma decay. reverse image search of reddit.com." /', 'thing_id': u't3_334fmf'}
posted:         <meta name="description" content="karma decay. reverse image search of reddit.com." /

        <meta name="keywords" content="image, search, reverse, similar" /
Good tld: True
No spamlinks in link: True
No text spam: True

        <meta name="keywords" content="image, search, reverse, similar" / IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '        <meta name="keywords" content="image, search, reverse, similar" /', 'thing_id': u't3_334fmf'}
posted:         <meta name="keywords" content="image, search, reverse, similar" /

        <link href="http://static.karmadecay.com/css/style.css?v=1.30" media="screen" rel="stylesheet" type="text/css" /
Good tld: True
No spamlinks in link: True
No text spam: True

        <link href="http://static.karmadecay.com/css/style.css?v=1.30" media="screen" rel="stylesheet" type="text/css" / IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '        <link href="http://static.karmadecay.com/css/style.css?v=1.30" media="screen" rel="stylesheet" type="text/css" /', 'thing_id': u't3_334fmf'}
posted:         <link href="http://static.karmadecay.com/css/style.css?v=1.30" media="screen" rel="stylesheet" type="text/css" /

        <link rel="shortcut icon" href="http://static.karmadecay.com/favicon.ico" /
Good tld: True
No spamlinks in link: True
No text spam: True

        <link rel="shortcut icon" href="http://static.karmadecay.com/favicon.ico" / IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '        <link rel="shortcut icon" href="http://static.karmadecay.com/favicon.ico" /', 'thing_id': u't3_334fmf'}
posted:         <link rel="shortcut icon" href="http://static.karmadecay.com/favicon.ico" /

        <script type="text/javascript"
Good tld: True
No spamlinks in link: True
No text spam: True

        <script type="text/javascript" IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '        <script type="text/javascript"', 'thing_id': u't3_334fmf'}
posted:         <script type="text/javascript"


Good tld: True
No spamlinks in link: True
No text spam: True

 IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
link is NOT!!!!
  var _gaq = _gaq ||
Good tld: True
No spamlinks in link: True
No text spam: True

  var _gaq = _gaq ||  IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '  var _gaq = _gaq || ', 'thing_id': u't3_334fmf'}
posted:   var _gaq = _gaq ||

  _gaq.push'_setaccount', 'ua-2955508-13'
Good tld: True
No spamlinks in link: True
No text spam: True

  _gaq.push'_setaccount', 'ua-2955508-13' IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': "  _gaq.push'_setaccount', 'ua-2955508-13'", 'thing_id': u't3_334fmf'}
posted:   _gaq.push'_setaccount', 'ua-2955508-13'

  _gaq.push'_setdomainname', 'karmadecay.com'
Good tld: True
No spamlinks in link: True
No text spam: True

  _gaq.push'_setdomainname', 'karmadecay.com' IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': "  _gaq.push'_setdomainname', 'karmadecay.com'", 'thing_id': u't3_334fmf'}
posted:   _gaq.push'_setdomainname', 'karmadecay.com'

  _gaq.push'_setcustomvar', '1', 'ad type', 'h', '3'
Good tld: True
No spamlinks in link: True
No text spam: True

  _gaq.push'_setcustomvar', '1', 'ad type', 'h', '3' IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': "  _gaq.push'_setcustomvar', '1', 'ad type', 'h', '3'", 'thing_id': u't3_334fmf'}
posted:   _gaq.push'_setcustomvar', '1', 'ad type', 'h', '3'

  _gaq.push'_trackpageview'
Good tld: True
No spamlinks in link: True
No text spam: True

  _gaq.push'_trackpageview' IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': "  _gaq.push'_trackpageview'", 'thing_id': u't3_334fmf'}
posted:   _gaq.push'_trackpageview'

  function
Good tld: True
No spamlinks in link: True
No text spam: True

  function  IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '  function ', 'thing_id': u't3_334fmf'}
posted:   function

    var ga = document.createelement'script'; ga.type = 'text/javascript'; ga.async = true
Good tld: True
No spamlinks in link: True
No text spam: True

    var ga = document.createelement'script'; ga.type = 'text/javascript'; ga.async = true IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': "    var ga = document.createelement'script'; ga.type = 'text/javascript'; ga.async = true", 'thing_id': u't3_334fmf'}
posted:     var ga = document.createelement'script'; ga.type = 'text/javascript'; ga.async = true

    ga.src = 'https:' == document.location.protocol ? 'https://ssl' : 'http://www' + '.google-analytics.com/ga.js'
Good tld: True
No spamlinks in link: True
No text spam: True

    ga.src = 'https:' == document.location.protocol ? 'https://ssl' : 'http://www' + '.google-analytics.com/ga.js' IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': "    ga.src = 'https:' == document.location.protocol ? 'https://ssl' : 'http://www' + '.google-analytics.com/ga.js'", 'thing_id': u't3_334fmf'}
posted:     ga.src = 'https:' == document.location.protocol ? 'https://ssl' : 'http://www' + '.google-analytics.com/ga.js'

ga, s
Good tld: True
No spamlinks in link: True
No text spam: True

ga, s IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
link is NOT!!!!
  }
Good tld: True
No spamlinks in link: True
No text spam: True

  } IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
link is NOT!!!!

Good tld: True
No spamlinks in link: True
No text spam: True

 IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
link is NOT!!!!
        </script
Good tld: True
No spamlinks in link: True
No text spam: True

        </script IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '        </script', 'thing_id': u't3_334fmf'}
posted:         </script

        <script type="text/javascript" src="http://static.karmadecay.com/js/kd.js?v=1.30"></script
Good tld: True
No spamlinks in link: True
No text spam: True

        <script type="text/javascript" src="http://static.karmadecay.com/js/kd.js?v=1.30"></script IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '        <script type="text/javascript" src="http://static.karmadecay.com/js/kd.js?v=1.30"></script', 'thing_id': u't3_334fmf'}
posted:         <script type="text/javascript" src="http://static.karmadecay.com/js/kd.js?v=1.30"></script

        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script
Good tld: True
No spamlinks in link: True
No text spam: True

        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script', 'thing_id': u't3_334fmf'}
posted:         <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script

    </head
Good tld: True
No spamlinks in link: True
No text spam: True

    </head IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '    </head', 'thing_id': u't3_334fmf'}
posted:     </head

    <body
Good tld: True
No spamlinks in link: True
No text spam: True

    <body IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '    <body', 'thing_id': u't3_334fmf'}
posted:     <body

        <div id="topl"
Good tld: True
No spamlinks in link: True
No text spam: True

        <div id="topl" IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '        <div id="topl"', 'thing_id': u't3_334fmf'}
posted:         <div id="topl"

            <div class="r"
Good tld: True
No spamlinks in link: True
No text spam: True

            <div class="r" IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '            <div class="r"', 'thing_id': u't3_334fmf'}
posted:             <div class="r"

                <a href="/faq" title="about us">about us</a
Good tld: True
No spamlinks in link: True
No text spam: True

                <a href="/faq" title="about us">about us</a IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '                <a href="/faq" title="about us">about us</a', 'thing_id': u't3_334fmf'}
posted:                 <a href="/faq" title="about us">about us</a

                <a href="http://contactbyweb.com/karmadecay" title="contact us">contact</a
Good tld: True
No spamlinks in link: True
No text spam: True

                <a href="http://contactbyweb.com/karmadecay" title="contact us">contact</a IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '                <a href="http://contactbyweb.com/karmadecay" title="contact us">contact</a', 'thing_id': u't3_334fmf'}
posted:                 <a href="http://contactbyweb.com/karmadecay" title="contact us">contact</a

                <a href="/browser-tools" title="bookmarklet / add-ons / extensions / user scripts">browser tools</a
Good tld: True
No spamlinks in link: True
No text spam: True

                <a href="/browser-tools" title="bookmarklet / add-ons / extensions / user scripts">browser tools</a IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '                <a href="/browser-tools" title="bookmarklet / add-ons / extensions / user scripts">browser tools</a', 'thing_id': u't3_334fmf'}
posted:                 <a href="/browser-tools" title="bookmarklet / add-ons / extensions / user scripts">browser tools</a

            </div
Good tld: True
No spamlinks in link: True
No text spam: True

            </div IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '            </div', 'thing_id': u't3_334fmf'}
posted:             </div

        </div
Good tld: True
No spamlinks in link: True
No text spam: True

        </div IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '        </div', 'thing_id': u't3_334fmf'}
posted:         </div

        <div id="wr"
Good tld: True
No spamlinks in link: True
No text spam: True

        <div id="wr" IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '        <div id="wr"', 'thing_id': u't3_334fmf'}
posted:         <div id="wr"

            <div id="header"
Good tld: True
No spamlinks in link: True
No text spam: True

            <div id="header" IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '            <div id="header"', 'thing_id': u't3_334fmf'}
posted:             <div id="header"

                <h1><a href="/" title="karma decay - reverse image search of reddit.com"><img src="http://static.karmadecay.com/img/karmadecay-logo.jpg" alt="karma decay"></a><a href="/karma-decay-logo" title="learn more about karma decay logo."><img src="http://static.karmadecay.com/img/magnify.gif" alt="magnify logo"></a></h1
Good tld: True
No spamlinks in link: True
No text spam: True

                <h1><a href="/" title="karma decay - reverse image search of reddit.com"><img src="http://static.karmadecay.com/img/karmadecay-logo.jpg" alt="karma decay"></a><a href="/karma-decay-logo" title="learn more about karma decay logo."><img src="http://static.karmadecay.com/img/magnify.gif" alt="magnify logo"></a></h1 IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '                <h1><a href="/" title="karma decay - reverse image search of reddit.com"><img src="http://static.karmadecay.com/img/karmadecay-logo.jpg" alt="karma decay"></a><a href="/karma-decay-logo" title="learn more about karma decay logo."><img src="http://static.karmadecay.com/img/magnify.gif" alt="magnify logo"></a></h1', 'thing_id': u't3_334fmf'}
posted:                 <h1><a href="/" title="karma decay - reverse image search of reddit.com"><img src="http://static.karmadecay.com/img/karmadecay-logo.jpg" alt="karma decay"></a><a href="/karma-decay-logo" title="learn more about karma decay logo."><img src="http://static.karmadecay.com/img/magnify.gif" alt="magnify logo"></a></h1

                <h3>reverse image search of reddit.com&nbsp;beta</h3
Good tld: True
No spamlinks in link: True
No text spam: True

                <h3>reverse image search of reddit.com&nbsp;beta</h3 IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '                <h3>reverse image search of reddit.com&nbsp;beta</h3', 'thing_id': u't3_334fmf'}
posted:                 <h3>reverse image search of reddit.com&nbsp;beta</h3

            </div
Good tld: True
No spamlinks in link: True
No text spam: True

            </div IS CLEAN

retrieving: http://www.reddit.com/comments/334fmf.json
params: None
data: None
retrieving: http://www.reddit.com/api/comment/.json
params: None
data: {'text': '            </div', 'thing_id': u't3_334fmf'}
posted:             </div

**Comment by jacobstein123** [comment]
To diagnose this issue, I'm making it so the program will print what it was trying to reply if it gets this error. Comment the attempted reply here when the error recurs, and I'll try to get to the bottom of this.
