### ISSUE TITLE
search engines commented out

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#57]
```
from .search import (
    #get_google_results,
    #get_bing_results,
    #get_yandex_results,
    #get_karmadecay_results,
    get_tineye_results,
```
https://github.com/tek0011/reddit_info_bot/blob/master/reddit_info_bot/__init__.py#L25-L31

Should these be commented out?

**Comment by nyov** [comment]
Yes, the code isn't in use (results are pulled through the heroku proxy)

**Comment by tek0011** [comment]
we probably want to change this at some point to now use it.  although I
have no idea what the heroku proxy is doing.  it was originally added
because digital ocean must get blocked by search engines

On Thu, Oct 8, 2015 at 10:46 AM, nyov <notifications@github.com> wrote:

> Yes, the code isn't in use (results are pulled through the heroku proxy)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/issues/57#issuecomment-146584237>
> .
>



-- 
Jeff

**Comment by nyov** [comment]
The proxy is basically doing what the commented-out code parts do, only remotely.
And yes, that'll have to happen as part of rewriting the search-code for the video support.

**Comment by nyov** [comment]
This code is gone now. (#85)
So I'm closing this.
