### ISSUE TITLE
Bot no longer checks past username mentions

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#64]
After starting the bot with the newest build, it should recognize that it has past username mentions, and handle them.  Right now it ignores them.

```

visiting comment stream 10/21 
0.000403165817261
tttooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo (100 comments)
finding username mentions: o!ooooo (7 comments)
Finished a round of comments. Waiting two seconds.
```

finding username mentions: o!ooooo **(7 comments)**

**Comment by nyov** [comment]
Hmm, this debugging line says, `o` = comment is too old, `!` = comment was on a sub not in my subreddits ([here](https://github.com/tek0011/reddit_info_bot/blob/f165dd3b45a59c1d486f1d0d65aa140e7ec67f4e/reddit_info_bot/__init__.py#L246-L251)).

The default timelimit is set to two minutes I think, after that they're considered too old.
I just checked if I mistakenly changed the behavior there, but it looks to me like that's how it worked before as well?

**Comment by tek0011** [comment]
Interesting.  Let me try changing the time limit to something large and see
what happens.  Thanks for the reply!

On Fri, Oct 9, 2015 at 8:31 AM, nyov <notifications@github.com> wrote:

> Hmm, this debugging line says, o = comment is too old, ! = comment was on
> a sub not in my subreddits (here
> <https://github.com/tek0011/reddit_info_bot/blob/f165dd3b45a59c1d486f1d0d65aa140e7ec67f4e/reddit_info_bot/__init__.py#L246-L251>
> ).
>
> The default timelimit is set to two minutes I think, after that they're
> considered too old.
> I just checked if I mistakenly changed the behavior there, but it looks to
> me like that's how it worked before as well?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/issues/64#issuecomment-146872257>
> .
>



-- 
Jeff

**Comment by tek0011** [comment]
I changed TIME_LIMIT_MINUTES to 500.  It processed the first request and then stopped at:
```
finding username mentions: !ooooo (6 comments)
```

**Comment by tek0011** [comment]
Well, it seems to work, but just ends up processing issue 

https://github.com/tek0011/reddit_info_bot/issues/63#issuecomment-146872619
