### ISSUE TITLE
Skipping other engines?

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#66]
So in this example it appears it searched Tineye and then no others?  Is that right?
```
tptpptppptpppptttttpptptptttttpttppppptpRptttptpppttttppppptttptpppptptptppptptttptppptpptpppttptptp (100 comments)
finding username mentions: Image-searching for http://i.imgur.com/xxxxx.gifv
Found imgur.com video - substituting with gif url: http://i.imgur.com/xxxxx.gif
Failed fetching Tineye results: No search results
replied to comment with more info>p!pp (5 comments)
Finished a round of comments. Waiting two seconds.
```

**Comment by nyov** [comment]
No, I'm sorry, I removed the previous code where it posted the search engines. Only tineye should have failed here. I can add some more logging to tell how many results per engine were found and such. Anything additional you would like to see there?

**Comment by nyov** [comment]
And switching out all the print statements for some serious logging + stats is on the agenda ;)
Then I'll invest more time to get it right.

**Comment by tek0011** [comment]
The new debugging is awesome btw.  So much easier to understand what is happening.
