### ISSUE TITLE
Spam not working. 

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#69]
This post was removed by rarchives, 

https://www.reddit.com/r/info_bot_nsfw/comments/3pjj0r/reply_spam_test/

because of the following spam (seems to all be TLD)

http://i.imgur.com/vfWsxtq.png

**Comment by tek0011** [comment]
I just realized you probably cant see if because you arent mod of that sub.

**Comment by nyov** [comment]
If both bots (rarchives and us) are using the same database, that could only mean ours is using an outdated one I think. Or a bug with the spam parsing, indeed. Will have to carefully check for both here.
