### ISSUE TITLE
Mark read - parser replies

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#75]
With the parser now working correctly, it replies back to info_bot_nsfw.  However it doesnt mark the replies as read, which makes it appear there are many unhandled requests.  Should set post replies to auto mark as read.

**Comment by nyov** [comment]
I haven't checked yet, do you know which messages are ignored and if they can safely be marked read? That was a conscious decision not to mark all the stuff read that it scans, if it isn't actually handled by the bot. But I can certainly amend that, or just have the bot forgot about those messages instead (change the logging) so they don't pop up again repeatedly.

**Comment by nyov** [comment]
Unless of course there is a mistake, and it doesn't mark something read that it actually handled?

**Comment by tek0011** [comment]
I think its marking correctly.  No need to worry about that for the time
being.  Sorry, really busy with a project production release this week.

On Tue, Oct 27, 2015 at 1:18 PM, nyov <notifications@github.com> wrote:

> Unless of course there is a mistake, and it doesn't mark something read
> that it actually handled?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/issues/75#issuecomment-151597213>
> .
>



-- 
Jeff

**Comment by nyov** [comment]
Fixed, messages should be correctly marked as read now.
