### ISSUE TITLE
lost my dev?

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#80]
have I lost you?

**Comment by nyov** [comment]
no, no, (I hope not).
Been a stressful december, and the new year wasn't much better so far. Finally put me out of commission these last two weeks or I'd have responded earlier by now.
I'll be back and shoot a proper mail in the next days, have to resolve some other issues first.
And I'll make sure to get something done in the next week. Thanks for the patience.

**Comment by tek0011** [comment]
No worries.  Take your time.  Your email is not working, was the only
concern.

**Comment by nyov** [comment]
I know (ISP thought I was gone too long, too, gotta straighten them out). Sorry!

**Comment by tek0011** [comment]
jaja np

On Sun, Jan 24, 2016 at 6:58 PM, nyov <notifications@github.com> wrote:

> I know (ISP thought I was gone too long, too, gotta straighten them out).
> Sorry!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/issues/80#issuecomment-174361906>
> .
>



-- 
Jeff

**Comment by nyov** [comment]
> jaja np

jaja? as in, [leck mich am arsch](https://www.youtube.com/watch?v=PHFBGO7s5Sk)?
hehe. well, I hope we're good :p
