### ISSUE TITLE
Error occured in image_search: 

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#83]
2016-02-28 13:57:21 [reddit_info_bot.reddit] ERROR: Error occured in image_search: spamfilter_lists() takes exactly 1 argument (0 given)

**Comment by tek0011** [comment]
This completely breaks the bot as it gets stuck in a loop trying over and over to complete the request.

**Comment by nyov** [comment]
I have notices that, and apologies. Please check the changes I made in #82, which includes the fix for that.

**Comment by nyov** [comment]
Deployed the update and this works now.
