### ISSUE TITLE
Bug - Blocked - 

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#90]
https://github.com/tek0011/reddit_info_bot/pull/88

2016-03-29 07:48:24 [reddit_info_bot.reddit] INFO: [N] Detected keyword(s) u/info_bot_nsfw in https://www.reddit.com/r/gilf/comments/4c0k9w/beautiful_in_lingerie/d1fu8s5
2016-03-29 07:48:24 [reddit_info_bot.reddit] ERROR: Error occured in image_search: No module named twisted.internet.default

**Comment by tek0011** [comment]
installed twisted

**Comment by tek0011** [comment]
installed libffi-devel
pip installed scrapy
pip install twisted

**Comment by tek0011** [comment]
pip install urllib3

all seems to be working now, although we should handle additional modules a bit better in the future.

**Comment by nyov** [comment]
Ah I could have noted those more specifically.
The bot can also be installed/upgraded with pip (and pull in dependencies like in this case). Maybe that would be better for the deployed version instead of using git? Then only putting the local configuration under version management, perhaps.
This command should work to install it:
`pip install --upgrade --user --compile 'https://github.com/tek0011/reddit_info_bot/zipball/master'`

**Comment by tek0011** [comment]
thats a fancy way to handle the dependencies.   I dont mind adding them
manually.  If it creates more work for you to change it, dont bother.  PS.
Sending you other half of the 125 later today.  Also replying back to your
email from 4 days ago, so we can move forward on the next thing.

thanks for the reply back.

On Tue, Mar 29, 2016 at 8:41 AM, nyov <notifications@github.com> wrote:

> Ah I could have noted those more specifically.
> The bot can also be installed/upgraded with pip (and pull in dependencies
> like in this case). Maybe that would be better for the deployed version
> instead of using git? Then only putting the local configuration under
> version management, perhaps.
> This command should work to install it:
> pip install --upgrade --user --compile '
> https://github.com/tek0011/reddit_info_bot/zipball/master'
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/issues/90#issuecomment-202898560>
>



-- 
Jeff

**Comment by nyov** [comment]
> If it creates more work for you to change it, dont bother.

Hm, if you don't want the easy "pip install" version, what would you propose to handle it better?
(Could also run that command to install it with dependencies, but then keep using the git version and ignore the pip-installed redditbot.)

And thank you too!

**Comment by tek0011** [comment]
No, what I mean, is I dont mind manually pip installing missing
dependencies.   any manual interaction I have with coding/this
bot/anything, helps me further understanding coding in general.  So even
though my main day to day job consists of writing code to automate things,
I still like to do things manually because Im still learning.

I dont mind manually pip installing dependencies, in order to learn.  I
dont foresee us needing a ton more anyway.

On Tue, Mar 29, 2016 at 9:26 AM, nyov <notifications@github.com> wrote:

> If it creates more work for you to change it, dont bother.
>
> Hm, if you don't want the easy "pip install" version, what would you
> propose to handle it better?
> (Could also run that command to install it with dependencies, but then
> keep using the git version and ignore the pip-installed redditbot.)
>
> And thank you too!
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/issues/90#issuecomment-202918715>
>



-- 
Jeff
