### ISSUE TITLE
[imagesearch-bing] INFO: Ignoring Bing result with bad response status (404):

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#93]
[imagesearch-bing] INFO: Ignoring Bing result with bad response status (404):

For all Bing searches

**Comment by nyov** [comment]
Some 404s or other errors from the link-check are to be expected - it means the page does no longer exist and is removed from the list of results. This is as you requested for the Milestone.
(Though I can probably downgrade those to DEBUG-level messages as they are no real errors in the end).

If all results get filtered out as 404 that would be very strange, and indicate a problem or even a datacenter-wide (outgoing) http block.
From looking at the logs that doesn't seem to be the case (there were some Bing results in the reddit post in all cases), so I don't think there is problem here?
