### ISSUE TITLE
No Wordcloud on response

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#95]
https://www.reddit.com/r/info_bot_nsfw/comments/4k234r/httpiimgurcomlfz9zipjpg/d3bh1g5

**Comment by nyov** [comment]
Did you set up the imgur account ID in config? Then it should be as simple as setting `BOTCMD_WORDCLOUD_ENABLED` to `True` in the settings. I disabled it there, so it would work in the meantime.

**Comment by tek0011** [comment]
oh jeez.  i totally forgot.  but we probably need to fix the other issues
as they are more important.  Ill try again, a little later, with the
account ID

On Thu, May 19, 2016 at 8:49 AM, nyov <notifications@github.com> wrote:

> Did you set up the imgur account ID in config? Then it should be as simple
> as setting BOTCMD_WORDCLOUD_ENABLED to True in the settings. I disabled
> it there, so it would work in the meantime.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/issues/95#issuecomment-220329673>
>



-- 
Jeff

**Comment by nyov** [comment]
This is the registration page to get a client ID
https://api.imgur.com/oauth2/addclient

**Comment by nyov** [comment]
Wordclouds seem to work now, so I'll close this.
