### ISSUE TITLE
Not filtering all spam links

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#96]
https://www.reddit.com/r/info_bot_nsfw/comments/4k234r/httpiimgurcomlfz9zipjpg/d3bh1g5

**Comment by nyov** [comment]
I've followed up on that; spambot.rarchives.com said it was removed because of finding the ".es" TLD in the text, and checking the source of the banned post there is only one URL with ".es" in it -- in the direct image link.
It seems I have forgotten to include those URLs in the spamcheck.
