### ISSUE TITLE
AttributeError: 'ImgurClient' object has no attribute 'upload'

### ISSUE THREAD

**Issue by tek0011** [tek0011/reddit_info_bot#99]
```
Traceback (most recent call last):
  File "info_bot.py", line 7, in <module>
    execute()
  File "/etc/reddit-infobot/reddit_info_bot/cli.py", line 268, in execute
    exitcode = cmd(**cmdargs)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 134, in wrapped
    return do_setup(settings, command, *args, **kwargs)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 117, in do_setup
    command(settings, *a, **kw)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 194, in cmd_run
    handle_bot_action(messages, settings, account1, account2, subreddit_list, comments_seen, 'find_username_mentions')
  File "/etc/reddit-infobot/reddit_info_bot/reddit.py", line 477, in handle_bot_action
    account1=account, account2=account2)
  File "/etc/reddit-infobot/reddit_info_bot/commands.py", line 286, in cmd_imagesearch
    idata = image_upload(client, wordcloud_image, config)
  File "/etc/reddit-infobot/reddit_info_bot/imgur.py", line 37, in image_upload
    image_meta = client.upload(image, config, anon)
AttributeError: 'ImgurClient' object has no attribute 'upload'
```

**Comment by tek0011** [comment]
This completely breaks the bot.

**Comment by nyov** [comment]
That happens when the `imgurpython` library is too old.
Version 1.1.8 is required, but the maintainers apparently *still* haven't updated their PyPI packages.

In the meantime it can be downloaded here: https://github.com/Imgur/imgurpython/zipball/1.1.8
or install via pip:
`pip install 'https://github.com/Imgur/imgurpython/zipball/1.1.8'`

**Comment by tek0011** [comment]
Ah yes thank you.  :)  I finally have a dedicated host and a couple days to
work on this.  Thanks for fast reply.

On Mon, Jul 11, 2016 at 2:45 PM, nyov <notifications@github.com> wrote:

> That happens when the imgurpython library is too old.
> Version 1.1.8 is required, but the maintainers apparently *still* haven't
> updated their PyPI packages.
>
> In the meantime it can be downloaded here:
> https://github.com/Imgur/imgurpython/zipball/1.1.8
> or install via pip:
> pip install 'https://github.com/Imgur/imgurpython/zipball/1.1.8'
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tek0011/reddit_info_bot/issues/99#issuecomment-231843063>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABCOXM6ZbjSnceLT11tb1ObQz05igJI0ks5qUp1EgaJpZM4JJrEr>
> .
>



-- 
Jeff
